[project]
name = "app"
version = "0.1.0"
description = "This is a MiniKit inspired by the scikit learn framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "scikit-learn>=1.7.2",
]
